
const translations = {
    ru: {
        'app-title': 'Физическая песочница',
        'move-title': 'Переместить (точно)',
        'finger-title': 'Палец (физика)',
        'box-title': 'Коробка',
        'circle-title': 'Круг', // NEW
        'polygon-title': 'Полигон',
        'brush-title': 'Кисть',
        'weld-title': 'Сварка',
        'spring-title': 'Пружина',
        'rod-title': 'Стержень', // NEW
        'tnt-small-title': 'Малый ТНТ',
        'tnt-medium-title': 'Средний ТНТ',
        'tnt-large-title': 'Мощный ТНТ',
        'water-title': 'Вода',
        'sand-title': 'Песок',
        'eraser-title': 'Ластик',
        'save-title': 'Сохранить игру',
        'load-title': 'Загрузить игру',
        'settings-title': 'Настройки',
        'play-title': 'Воспроизвести',
        'pause-title': 'Пауза',
        'clear-all-title': 'Очистить всё',
        'confirm-title': 'Подтверждение',
        'confirm-clear-all': 'Вы уверены, что хотите всё очистить? Это действие необратимо.',
        'world-cleared-message': 'Мир очищен!',
        'confirm-button': 'Подтвердить',
        'cancel-button': 'Отмена',
        'gravity-label': 'Гравитация:',
        'liquid-effect-label': 'Эффект жидкости:',
        'show-hitboxes-label': 'Показывать хитбоксы:',
        'ui-sounds-label': 'Звуки UI:',
        'object-sounds-label': 'Звуки объектов:',
        'environment-sounds-label': 'Звуки окружения:',
        'density-setting-label': 'Плотность объектов:',
        'tnt-small-power-label': 'Сила малого ТНТ:',
        'tnt-medium-power-label': 'Сила среднего ТНТ:',
        'tnt-large-power-label': 'Сила мощного ТНТ:',
        'color-label': 'Цвет:',
        'friction-label': 'Трение:',
        'restitution-label': 'Упругость:',
        'density-label': 'Плотность:',
        'resistance-label': 'Сопротивление:',
        'static-label': 'Неподвижный:',
        'delete-button': 'Удалить',
        'stiffness-label': 'Жёсткость:',
        'damping-label': 'Затухание:',
        'delete-spring-button': 'Удалить пружину',
        'spring-length-label': 'Длина:',
        'spring-fixed-label': 'Фиксированная:',
        'brush-size-label': 'Толщина:',
        'enable-motor-label': 'Включить мотор:', // NEW
        'motor-speed-label': 'Скорость:', // NEW
        'grip-label': 'Сцепление:', // NEW
        'low-fps-title': 'Низкая производительность',
        'low-fps-message': 'Обнаружен низкий FPS. Большое количество воды может замедлять симуляцию. Что вы хотите сделать?',
        'delete-water-button': 'Удалить всю воду',
        'pause-button': 'Поставить на паузу',
        'do-nothing-button': 'Ничего не делать',
        'dont-ask-again-button': 'Больше не спрашивать',
        'coins-label': 'Резонансы',
        'reward-menu-title': 'Награды за просмотр рекламы',
        'reward-amount-label': 'Награда: {amount} Резонансов',
        'watch-ad-button': 'Смотреть рекламу ({progress})',
        'reward-claimed': 'Получено!',
        'claim-reward': 'Получить!',
        'close-button': 'X',
        'watching-ad-countdown': 'Смотрим рекламу: {time} сек',
        'loading-ad': 'Загрузка...',
        'ad-failed-retry': 'Ошибка. Повторить?',
        'save-game-title': 'Сохранить игру',
        'load-game-title': 'Загрузить игру',
        'save-slot-label': 'Слот',
        'empty-slot-label': 'Пусто',
        'save-button': 'Сохранить',
        'load-button': 'Загрузить',
        'game-saved-message': 'Игра успешно сохранена!',
        'game-save-failed-message': 'Ошибка сохранения игры!',
        'game-loaded-message': 'Игра успешно загружена!',
        'game-load-failed-message': 'Ошибка загрузки игры!',
        'slot-empty-message': 'Этот слот пуст.',
        'slot-cleared-message': 'Слот сохранения очищен.',
        'confirm-delete-save-message': 'Вы уверены, что хотите сбросить этот слот? Весь прогресс в нем будет потерян.',
        'play-time': 'Время игры',
        'objects': 'Объекты',
        'water': 'Вода',
        'sand': 'Песок',
        'unlock-for-price': 'Разблокировать за {price}',
        'locked': 'Заблокировано',
        'not-enough-resonances': 'Недостаточно Резонансов',
        'polygon-self-intersection-error': 'Стороны полигона не должны пересекаться!',
        'category-physics': 'Физика мира',
        'velocity-iterations-label': 'Точность симуляции:',
        'position-iterations-label': 'Стабильность симуляции:',
        'category-graphics': 'Графика',
        'max-water-label': 'Макс. частиц воды:',
        'max-sand-label': 'Макс. частиц песка:',
        'water-color-label': 'Цвет воды:',
        'sand-color-label': 'Цвет песка:',
        'category-sound': 'Звук',
        'master-volume-label': 'Общая громкость:',
        'category-interface': 'Интерфейс',
        'show-debug-label': 'Показывать FPS и коорд.:',
        'exit-game-button': 'Выйти в меню',
        'confirm-exit-game': 'Вы уверены, что хотите выйти в главное меню? Несохраненный прогресс будет потерян.',
    },
    en: {
        'app-title': 'Physics Sandbox',
        'move-title': 'Move (precise)',
        'finger-title': 'Finger (physics)',
        'box-title': 'Box',
        'circle-title': 'Circle', // NEW
        'polygon-title': 'Polygon',
        'brush-title': 'Brush',
        'weld-title': 'Weld',
        'spring-title': 'Spring',
        'rod-title': 'Rod', // NEW
        'tnt-small-title': 'Small TNT',
        'tnt-medium-title': 'Medium TNT',
        'tnt-large-title': 'Large TNT',
        'water-title': 'Water',
        'sand-title': 'Sand',
        'eraser-title': 'Eraser',
        'save-title': 'Save Game',
        'load-title': 'Load Game',
        'settings-title': 'Settings',
        'play-title': 'Play',
        'pause-title': 'Pause',
        'clear-all-title': 'Clear All',
        'confirm-title': 'Confirmation',
        'confirm-clear-all': 'Are you sure you want to clear everything? This action cannot be undone.',
        'world-cleared-message': 'World cleared!',
        'confirm-button': 'Confirm',
        'cancel-button': 'Cancel',
        'gravity-label': 'Gravity:',
        'liquid-effect-label': 'Liquid effect:',
        'show-hitboxes-label': 'Show hitboxes:',
        'ui-sounds-label': 'UI Sounds:',
        'object-sounds-label': 'Object Sounds:',
        'environment-sounds-label': 'Environment Sounds:',
        'density-setting-label': 'Object Density:',
        'tnt-small-power-label': 'Small TNT Power:',
        'tnt-medium-power-label': 'Medium TNT Power:',
        'tnt-large-power-label': 'Large TNT Power:',
        'color-label': 'Color:',
        'friction-label': 'Friction:',
        'restitution-label': 'Restitution:',
        'density-label': 'Density:',
        'resistance-label': 'Resistance:',
        'static-label': 'Static:',
        'delete-button': 'Delete',
        'stiffness-label': 'Stiffness:',
        'damping-label': 'Damping:',
        'delete-spring-button': 'Delete Spring',
        'spring-length-label': 'Length:',
        'spring-fixed-label': 'Fixed:',
        'brush-size-label': 'Thickness:',
        'enable-motor-label': 'Enable Motor:', // NEW
        'motor-speed-label': 'Speed:', // NEW
        'grip-label': 'Grip:', // NEW
        'low-fps-title': 'Low Performance',
        'low-fps-message': 'Low FPS detected. A large amount of water can slow down the simulation. What would you like to do?',
        'delete-water-button': 'Delete All Water',
        'pause-button': 'Pause',
        'do-nothing-button': 'Do Nothing',
        'dont-ask-again-button': 'Don\'t ask again',
        'coins-label': 'Resonances',
        'reward-menu-title': 'Rewards for Ads',
        'reward-amount-label': 'Reward: {amount} Resonances',
        'watch-ad-button': 'Watch Ad ({progress})',
        'reward-claimed': 'Claimed!',
        'claim-reward': 'Claim!',
        'close-button': 'X',
        'watching-ad-countdown': 'Watching ad: {time} sec',
        'loading-ad': 'Loading...',
        'ad-failed-retry': 'Error. Retry?',
        'save-game-title': 'Save Game',
        'load-game-title': 'Load Game',
        'save-slot-label': 'Slot',
        'empty-slot-label': 'Empty',
        'save-button': 'Save',
        'load-button': 'Load',
        'game-saved-message': 'Game saved successfully!',
        'game-save-failed-message': 'Failed to save game!',
        'game-loaded-message': 'Game loaded successfully!',
        'game-load-failed-message': 'Failed to load game!',
        'slot-empty-message': 'This slot is empty.',
        'slot-cleared-message': 'Save slot cleared.',
        'confirm-delete-save-message': 'Are you sure you want to reset this slot? All progress will be lost.',
        'play-time': 'Play Time',
        'objects': 'Objects',
        'water': 'Water',
        'sand': 'Sand',
        'unlock-for-price': 'Unlock for {price}',
        'locked': 'Locked',
        'not-enough-resonances': 'Not enough Resonances',
        'polygon-self-intersection-error': 'Polygon edges cannot intersect!',
        'category-physics': 'World Physics',
        'velocity-iterations-label': 'Simulation Accuracy:',
        'position-iterations-label': 'Simulation Stability:',
        'category-graphics': 'Graphics',
        'max-water-label': 'Max Water Particles:',
        'max-sand-label': 'Max Sand Particles:',
        'water-color-label': 'Water Color:',
        'sand-color-label': 'Sand Color:',
        'category-sound': 'Sound',
        'master-volume-label': 'Master Volume:',
        'category-interface': 'Interface',
        'show-debug-label': 'Show FPS & Coords:',
        'exit-game-button': 'Exit to Menu',
        'confirm-exit-game': 'Are you sure you want to exit to the main menu? Unsaved progress will be lost.',
    },
    tr: {
        'app-title': 'Fizik Sandbox',
        'move-title': 'Taşı (hassas)',
        'finger-title': 'Parmak (fizik)',
        'box-title': 'Kutu',
        'circle-title': 'Daire', // NEW
        'polygon-title': 'Çokgen',
        'brush-title': 'Fırça',
        'weld-title': 'Kaynak',
        'spring-title': 'Yay',
        'rod-title': 'Çubuk', // NEW
        'tnt-small-title': 'Küçük TNT',
        'tnt-medium-title': 'Orta TNT',
        'tnt-large-title': 'Büyük TNT',
        'water-title': 'Su',
        'sand-title': 'Kum',
        'eraser-title': 'Silgi',
        'save-title': 'Oyunu Kaydet',
        'load-title': 'Oyunu Yükle',
        'settings-title': 'Ayarlar',
        'play-title': 'Oynat',
        'pause-title': 'Duraklat',
        'clear-all-title': 'Tümünü Temizle',
        'confirm-title': 'Onay',
        'confirm-clear-all': 'Her şeyi temizlemek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
        'world-cleared-message': 'Dünya temizlendi!',
        'confirm-button': 'Onayla',
        'cancel-button': 'İptal',
        'gravity-label': 'Yerçekimi:',
        'liquid-effect-label': 'Sıvı efekti:',
        'show-hitboxes-label': 'Sınırları göster:',
        'ui-sounds-label': 'Arayüz Sesleri:',
        'object-sounds-label': 'Nesne Sesleri:',
        'environment-sounds-label': 'Ortam Sesleri:',
        'density-setting-label': 'Nesne Yoğunluğu:',
        'tnt-small-power-label': 'Küçük TNT Gücü:',
        'tnt-medium-power-label': 'Orta TNT Gücü:',
        'tnt-large-power-label': 'Büyük TNT Gücü:',
        'color-label': 'Renk:',
        'friction-label': 'Sürtünme:',
        'restitution-label': 'Esneklik:',
        'density-label': 'Yoğunluk:',
        'resistance-label': 'Direnç:',
        'static-label': 'Sabit:',
        'delete-button': 'Sil',
        'stiffness-label': 'Sertlik:',
        'damping-label': 'Sönümleme:',
        'delete-spring-button': 'Yayı Sil',
        'spring-length-label': 'Uzunluk:',
        'spring-fixed-label': 'Sabit:',
        'brush-size-label': 'Kalınlık:',
        'enable-motor-label': 'Motoru Etkinleştir:', // NEW
        'motor-speed-label': 'Hız:', // NEW
        'grip-label': 'Yol Tutuşu:', // NEW
        'low-fps-title': 'Düşük Performans',
        'low-fps-message': 'Düşük FPS algılandı. Çok miktarda su simülasyonu yavaşlatabilir. Ne yapmak istersiniz?',
        'delete-water-button': 'Tüm Suyu Sil',
        'pause-button': 'Duraklat',
        'do-nothing-button': 'Hiçbir Şey Yapma',
        'dont-ask-again-button': 'Tekrar sorma',
        'coins-label': 'Rezonanslar',
        'reward-menu-title': 'Reklam Ödülleri',
        'reward-amount-label': 'Ödül: {amount} Rezonans',
        'watch-ad-button': 'Reklam İzle ({progress})',
        'reward-claimed': 'Alındı!',
        'claim-reward': 'Al!',
        'close-button': 'X',
        'watching-ad-countdown': 'Reklam izleniyor: {time} sn',
        'loading-ad': 'Yükleniyor...',
        'ad-failed-retry': 'Hata. Tekrar dene?',
        'save-game-title': 'Oyunu Kaydet',
        'load-game-title': 'Oyunu Yükle',
        'save-slot-label': 'Yuva',
        'empty-slot-label': 'Boş',
        'save-button': 'Kaydet',
        'load-button': 'Yükle',
        'game-saved-message': 'Oyun başarıyla kaydedildi!',
        'game-save-failed-message': 'Oyun kaydedilemedi!',
        'game-loaded-message': 'Oyun başarıyla yüklendi!',
        'game-load-failed-message': 'Oyun yüklenemedi!',
        'slot-empty-message': 'Bu yuva boş.',
        'slot-cleared-message': 'Kayıt yuvası temizlendi.',
        'confirm-delete-save-message': 'Bu yuvayı sıfırlamak istediğinizden emin misiniz? Tüm ilerleme kaybolacak.',
        'play-time': 'Oynama Süresi',
        'objects': 'Nesneler',
        'water': 'Su',
        'sand': 'Kum',
        'unlock-for-price': '{price} karşılığında aç',
        'locked': 'Kilitli',
        'not-enough-resonances': 'Yetersiz Rezonans',
        'polygon-self-intersection-error': 'Çokgen kenarları kesişemez!',
        'category-physics': 'Dünya Fiziği',
        'velocity-iterations-label': 'Simülasyon Hassasiyeti:',
        'position-iterations-label': 'Simülasyon Kararlılığı:',
        'category-graphics': 'Grafikler',
        'max-water-label': 'Maks. Su Parçacığı:',
        'max-sand-label': 'Maks. Kum Parçacığı:',
        'water-color-label': 'Su Rengi:',
        'sand-color-label': 'Kum Rengi:',
        'category-sound': 'Ses',
        'master-volume-label': 'Ana Ses Seviyesi:',
        'category-interface': 'Arayüz',
        'show-debug-label': 'FPS ve Koor. Göster:',
        'exit-game-button': 'Menüye Dön',
        'confirm-exit-game': 'Ana menüye dönmek istediğinizden emin misiniz? Kaydedilmemiş ilerleme kaybolacak.',
    }
};

let currentLang = 'ru'; // default

export function setLang(lang) {
    if (translations[lang]) {
        currentLang = lang;
    } else {
        currentLang = 'en'; // fallback to English
    }
    console.log(`Language set to: ${currentLang}`);
}

export function t(key, params = {}) {
    let translation = translations[currentLang]?.[key] || translations['en'][key] || `[${key}]`;
    for (const p in params) {
        translation = translation.replace(`{${p}}`, params[p]);
    }
    return translation;
}